namespace: bitcoin
resources:
  - bitcoin-namespace.yaml
  - production-issuer.yaml
  - staging-issuer.yaml
  - nioctib-deployment.yaml
  - bitcoind-password-secret.enc.yaml
  - btc-rpc-explorer-deployment.yaml
